version: 2
snapshot:
  version_template: "v{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^examples:'
builds:
  - id: minibridge
    binary: minibridge
    goos:
    - linux
    - darwin
    goarch:
    - amd64
    env:
    - CGO_ENABLED=0

archives:
  - id: minibridge
    formats: ['binary']
    builds:
    - minibridge

signs:
  - artifacts: checksum
    args: ["-u", "0C3214A61024881F5CA1F5F056EDB08A11DCE325", "--output", "${signature}", "--detach-sign", "${artifact}"]
